### ISSUE TITLE
Patient ID splits for training, validation, and test sets?

### ISSUE THREAD

**Issue by blackboxradiology** [epierson9/pain-disparities#6]
Looking to recreate some of your team's findings. Is it possible to share the same patient ID splits that were used in these experiments? Thank you for your consideration.

**Comment by epierson9** [comment]
See the `make_train_val_test_hold_out_set` function in `constants_and_util.py`! Note that while this partitions all patient IDs in the dataset, the datasets on which we conduct analysis are slightly smaller because we filter for patients who have covariates described in the paper. The results on the paper are computed on the subtly named `BLINDED_HOLD_OUT_DO_NOT_USE` set.
